{{- $gpuKEY := "nvidia.com/gpu" -}}
{{- $IgpuKEY := "gpu.intel.com/i915" -}}
{{- $encoder := "x264enc" -}}
{{- if or (and (hasKey .Values.resources "requests") (hasKey .Values.resources.requests $gpuKEY)) (and (hasKey .Values.resources "limits") (hasKey .Values.resources.limits $gpuKEY)) }}
{{- $encoder = "nvh264enc" -}}
{{- else if or (and (hasKey .Values.resources "requests") (hasKey .Values.resources.requests $IgpuKEY)) (and (hasKey .Values.resources "limits") (hasKey .Values.resources.limits $IgpuKEY)) }}
{{- $encoder = "vah264enc" -}}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-cm-{{ include "chemistry-pack.fullname" . }}
  labels:
    {{- include "chemistry-pack.labels" . | nindent 4 }}
data:
  SELKIES_BASIC_AUTH_USER: {{ .Values.settings.user }}
  SELKIES_BASIC_AUTH_PASSWORD: {{ .Values.settings.password }}
  {{- if or (and (hasKey .Values.resources "requests") (hasKey .Values.resources.requests $IgpuKEY)) (and (hasKey .Values.resources "limits") (hasKey .Values.resources.limits $IgpuKEY)) }}
  VGL_DISPLAY: /dev/dri/card1
  {{- end }}
  KASMVNC_ENABLE: {{ quote .Values.settings.kasm }}
  SELKIES_ENCODER: {{ .Values.settings.encoder | default $encoder | quote }}
  {{- with .Values.envs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if not .Values.settings.kasm }}
  SELKIES_TURN_HOST: {{ .Values.settings.turn.host | default .Values.settings.turn.ip }}
  SELKIES_TURN_PORT: {{ .Values.settings.turn.basePort | quote }}
  SELKIES_TURN_PROTOCOL: "udp"
  SELKIES_TURN_TLS: "false"
  TURN_MIN_PORT: {{ .Values.settings.turn.minPort | quote }}
  TURN_MAX_PORT: {{ .Values.settings.turn.maxPort | quote }}
  {{- end }}
