apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ include "chemistry-pack.fullname" . }}
  labels:
    {{- include "chemistry-pack.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.pvc.mode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClass }}